/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Splodeman (https://sketchfab.com/Splodeman)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-veteran-87349c1ea8fc4a4c9ca06f0899d7f56d
title: Old Veteran
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group>
                  <primitive object={nodes._rootJoint} />
                  <group position={[0, 92, -1.15]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group rotation={[-Math.PI / 2, 0, 0]} />
                  <group position={[0, 0, 0.33]} rotation={[Math.PI / 2, 1.57, 0]} />
                  <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Material_61} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
