import { AttackEquip } from './types'


const Attack: AttackEquip[] = [
    {
        type: "battle",
        name: "Double 1",
        imagePath: "/images/battles/equipment-pack/attack/pack1/1.png",
        supply: 300,
        limitSupplyPerUser: 4,
        priceInDENA: 500,
        level: 5,
        strength: -0.2,
        endurance: -0.6,
        agility: 2,
        precision: 8.3,
        intelligance: 9.2,
        willpower: 12,
        onehand: -0.2,
        twohand: 0.1,
        shield: 2.2,
        range: 4,
        dual: 7,
        polearms: 4.3,
        leadership: 0.3,
        coach: 5,
        cook: 0,
        medical: 0,
        smith: 0,
        torture: -0.2,
    },
    {
        type: "battle",
        name: "Double 2",
        imagePath: "/images/battles/equipment-pack/attack/pack1/2.png",
        supply: 400,
        limitSupplyPerUser: 2,
        priceInDENA: 400,
        level: 4,
        strength: -0.1,
        endurance: -0.5,
        agility: 1,
        precision: 8.5,
        intelligance: 9.1,
        willpower: 11,
        onehand: 0.1,
        twohand: 0.2,
        shield: 2.3,
        range: 3,
        dual: 8,
        polearms: 3.9,
        leadership: 0.4,
        coach: 4,
        cook: 1,
        medical: 2,
        smith: 1,
        torture: 0.1,
    },
    {
        type: "battle",
        name: "Double 3",
        imagePath: "/images/battles/equipment-pack/attack/pack1/3.png",
        supply: 500,
        limitSupplyPerUser: 1.5,
        priceInDENA: 300,
        level: 3,
        strength: 1,
        endurance: -0.4,
        agility: 2,
        precision: 8.7,
        intelligance: 8.9,
        willpower: 9,
        onehand: 1,
        twohand: 0.3,
        shield: 1.9,
        range: 2,
        dual: 9,
        polearms: 3.7,
        leadership: 0.5,
        coach: 3,
        cook: 2,
        medical: 4,
        smith: -1,
        torture: 1,
    },
    {
        type: "battle",
        name: "Double 4",
        imagePath: "/images/battles/equipment-pack/attack/pack1/4.png",
        supply: 100,
        limitSupplyPerUser: 1,
        priceInDENA: 200,
        level: 1,
        strength: 2,
        endurance: -0.3,
        agility: 1,
        precision: 8.1,
        intelligance: 9,
        willpower: 10,
        onehand: 0.3,
        twohand: 0.4,
        shield: 2.1,
        range: 5,
        dual: 6,
        polearms: 4.1,
        leadership: 0.2,
        coach: 2,
        cook: 3,
        medical: 5,
        smith: -2,
        torture: 0.3,
    },
    {
        type: "battle",
        name: "Double 5",
        imagePath: "/images/battles/equipment-pack/attack/pack1/5.png",
        supply: 200,
        limitSupplyPerUser: 3,
        priceInDENA: 100,
        level: 1,
        strength: 3,
        endurance: -0.2,
        agility: 2,
        precision: 7.9,
        intelligance: 9.3,
        willpower: 14,
        onehand: 0.4,
        twohand: 0.5,
        shield: 2,
        range: 1,
        dual: 5,
        polearms: 4.5,
        leadership: 0.1,
        coach: 1,
        cook: 4,
        medical: 2,
        smith: -3,
        torture: 0.4,
    },
    {
        type: "battle",
        name: "Spear 1",
        imagePath: "/images/battles/equipment-pack/attack/pack2/1.png",
        supply: 400,
        limitSupplyPerUser: 2,
        priceInDENA: 400,
        level: 5,
        strength: -0.1,
        endurance: -0.5,
        agility: 1,
        precision: 8.5,
        intelligance: 9.1,
        willpower: 11,
        onehand: 0.1,
        twohand: 0.2,
        shield: 2.3,
        range: 3,
        dual: 8,
        polearms: 3.9,
        leadership: 0.4,
        coach: 4,
        cook: 1,
        medical: 2,
        smith: 1,
        torture: 0.2,
    },
    {
        type: "battle",
        name: "Spear 2",
        imagePath: "/images/battles/equipment-pack/attack/pack2/2.png",
        supply: 300,
        limitSupplyPerUser: 4,
        priceInDENA: 500,
        level: 4,
        strength: -0.2,
        endurance: -0.6,
        agility: 2,
        precision: 8.3,
        intelligance: 9.2,
        willpower: 12,
        onehand: 0.2,
        twohand: 0.1,
        shield: 2.2,
        range: 4,
        dual: 7,
        polearms: 4.3,
        leadership: 0.3,
        coach: 5,
        cook: 0,
        medical: 0,
        smith: 0,
        torture: 0.1,
    },
    {
        type: "battle",
        name: "Spear 3",
        imagePath: "/images/battles/equipment-pack/attack/pack2/3.png",
        supply: 500,
        limitSupplyPerUser: 1.5,
        priceInDENA: 300,
        level: 3,
        strength: 1,
        endurance: -0.4,
        agility: 2,
        precision: 8.7,
        intelligance: 8.9,
        willpower: 9,
        onehand: 1,
        twohand: 0.3,
        shield: 1.9,
        range: 2,
        dual: 9,
        polearms: 3.7,
        leadership: 0.5,
        coach: 3,
        cook: 2,
        medical: 4,
        smith: -1,
        torture: 0.3,
    },
    {
        type: "battle",
        name: "Spear 4",
        imagePath: "/images/battles/equipment-pack/attack/pack2/4.png",
        supply: 100,
        limitSupplyPerUser: 1,
        priceInDENA: 200,
        level: 2,
        strength: 2,
        endurance: -0.3,
        agility: 1,
        precision: 8.1,
        intelligance: 9,
        willpower: 10,
        onehand: 0.3,
        twohand: 0.4,
        shield: 2.1,
        range: 5,
        dual: 6,
        polearms: 4.1,
        leadership: 0.2,
        coach: 2,
        cook: 3,
        medical: 5,
        smith: -2,
        torture: 0.4,
    },
    {
        type: "battle",
        name: "Spear 5",
        imagePath: "/images/battles/equipment-pack/attack/pack2/5.png",
        supply: 200,
        limitSupplyPerUser: 3,
        priceInDENA: 100,
        level: 1,
        strength: 3,
        endurance: -0.2,
        agility: 2,
        precision: 7.9,
        intelligance: 9.3,
        willpower: 14,
        onehand: 0.4,
        twohand: 0.5,
        shield: 2,
        range: 1,
        dual: 5,
        polearms: 4.5,
        leadership: 0.1,
        coach: 1,
        cook: 4,
        medical: 2,
        smith: -3,
        torture: 0.5,
    },
    {
        type: "battle",
        name: "Dega 1",
        imagePath: "/images/battles/equipment-pack/attack/pack3/1.png",
        supply: 500,
        limitSupplyPerUser: 1.5,
        priceInDENA: 300,
        level: 3,
        strength: 1,
        endurance: -0.4,
        agility: 2,
        precision: 8.7,
        intelligance: 8.9,
        willpower: 9,
        onehand: 1,
        twohand: 0.3,
        shield: 1.9,
        range: 2,
        dual: 9,
        polearms: 3.7,
        leadership: 0.5,
        coach: 3,
        cook: 2,
        medical: 4,
        smith: -1,
        torture: 2,
    },
    {
        type: "battle",
        name: "Dega 2",
        imagePath: "/images/battles/equipment-pack/attack/pack3/2.png",
        supply: 400,
        limitSupplyPerUser: 2,
        priceInDENA: 400,
        level: 4,
        strength: -0.1,
        endurance: -0.5,
        agility: 1,
        precision: 8.5,
        intelligance: 9.1,
        willpower: 11,
        onehand: 0.1,
        twohand: 0.2,
        shield: 2.3,
        range: 3,
        dual: 8,
        polearms: 3.9,
        leadership: 0.4,
        coach: 4,
        cook: 1,
        medical: 2,
        smith: 1,
        torture: 1,
    },
    {
        type: "battle",
        name: "Dega 3",
        imagePath: "/images/battles/equipment-pack/attack/pack3/3.png",
        supply: 200,
        limitSupplyPerUser: 3,
        priceInDENA: 100,
        level: 1,
        strength: 3,
        endurance: -0.2,
        agility: 2,
        precision: 7.9,
        intelligance: 9.3,
        willpower: 14,
        onehand: 0.4,
        twohand: 0.5,
        shield: 2,
        range: 1,
        dual: 5,
        polearms: 4.5,
        leadership: 0.1,
        coach: 1,
        cook: 4,
        medical: 2,
        smith: -3,
        torture: 2,
    },
    {
        type: "battle",
        name: "Dega 4",
        imagePath: "/images/battles/equipment-pack/attack/pack3/4.png",
        supply: 300,
        limitSupplyPerUser: 4,
        priceInDENA: 500,
        level: 5,
        strength: -0.2,
        endurance: -0.6,
        agility: 2,
        precision: 8.3,
        intelligance: 9.2,
        willpower: 12,
        onehand: 0.2,
        twohand: 0.1,
        shield: 2.2,
        range: 4,
        dual: 7,
        polearms: 4.3,
        leadership: 0.3,
        coach: 5,
        cook: 0,
        medical: 0,
        smith: 0,
        torture: 2,
    },
    {
        type: "battle",
        name: "Dega 5",
        imagePath: "/images/battles/equipment-pack/attack/pack3/5.png",
        supply: 100,
        limitSupplyPerUser: 1,
        priceInDENA: 200,
        level: 2,
        strength: 2,
        endurance: -0.3,
        agility: 1,
        precision: 8.1,
        intelligance: 9,
        willpower: 10,
        onehand: 0.3,
        twohand: 0.4,
        shield: 2.1,
        range: 5,
        dual: 6,
        polearms: 4.1,
        leadership: 0.2,
        coach: 3,
        cook: 3,
        medical: 5,
        smith: -2,
        torture: 1,
    },
]

export default Attack