export type AttackEquip = {
    type: string
    name: string
    imagePath: string
    supply: number
    limitSupplyPerUser: number
    priceInDENA: number
    level: number
    strength: number
    endurance: number
    agility: number
    precision: number
    intelligance: number
    willpower: number
    onehand: number
    twohand: number
    shield: number
    range: number
    dual: number
    polearms: number
    leadership: number
    coach: number
    cook: number
    medical: number
    smith: number
    torture: number
}
export type DefenseEquip = {
    type: string
    name: string
    imagePath: string
    supply: number
    limitSupplyPerUser: number
    priceInDENA: number
    level: number
    strength: number
    endurance: number
    agility: number
    precision: number
    intelligance: number
    willpower: number
    onehand: number
    twohand: number
    shield: number
    range: number
    dual: number
    polearms: number
    leadership: number
    coach: number
    cook: number
    medical: number
    smith: number
    torture: number
}
export type AnimalList = {
    type: string
    name: string
    imagePath: string
    supply: number
    limitSupplyPerUser: number
    priceInDENA: number
    level: number
    strength: number
    endurance: number
    agility: number
    precision: number
    intelligance: number
    willpower: number
    onehand: number
    twohand: number
    shield: number
    range: number
    dual: number
    polearms: number
    leadership: number
    coach: number
    cook: number
    medical: number
    smith: number
    torture: number
}
export type Equip = {
    type: string
    name: string
    imagePath: string
    supply: number
    limitSupplyPerUser: number
    priceInDENA: number
    level: number
    strength: number
    endurance: number
    agility: number
    precision: number
    intelligance: number
    willpower: number
    onehand: number
    twohand: number
    shield: number
    range: number
    dual: number
    polearms: number
    leadership: number
    coach: number
    cook: number
    medical: number
    smith: number
    torture: number
}