/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: geek3d (https://sketchfab.com/geek3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/5b25862dc8eb4496aa6f99563be6eea8
title: gladiator
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01} />
          <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01} />
          <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01} />
          <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01} />
          <group scale={0.01}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes['MHead_MHead#Mat0_0'].geometry}
              material={materials.MHeadMat0}
              skeleton={nodes['MHead_MHead#Mat0_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['MBody_MBody#Mat0_0'].geometry}
              material={materials.MBodyMat0}
              skeleton={nodes['MBody_MBody#Mat0_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['MArmor_MArmor#Mat0_0'].geometry}
              material={materials.MArmorMat0}
              skeleton={nodes['MArmor_MArmor#Mat0_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['MGauntlets_MGauntlets#Mat0_0'].geometry}
              material={materials.MGauntletsMat0}
              skeleton={nodes['MGauntlets_MGauntlets#Mat0_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['MLHand_MLHand#Mat0_0'].geometry}
              material={materials.MLHandMat0}
              skeleton={nodes['MLHand_MLHand#Mat0_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['MRHand_MRHand#Mat0_0'].geometry}
              material={materials.MRHandMat0}
              skeleton={nodes['MRHand_MRHand#Mat0_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['MBoots_MBoots#Mat0_0'].geometry}
              material={materials.MBootsMat0}
              skeleton={nodes['MBoots_MBoots#Mat0_0'].skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
