/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nyilonelycompany (https://sketchfab.com/Nyilonelycompany)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sword-warrior-n-cd0235388b9a4f2eb2c19d19ee5cc05d
title: Sword warrior N⚔🤺
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.36, 1.05, 0.5]} rotation={[2.91, 0.09, -1.32]} scale={[0.11, 0.12, 0.11]}>
            <group position={[0.13, 0, 0]} rotation={[0, -0.03, 0]} scale={[0.19, 0.03, 4.32]}>
              <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
            </group>
            <group position={[-0.06, 0, 4.34]} rotation={[0, 0.06, 0]} scale={[0.56, 0.28, 0.06]}>
              <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
            </group>
            <group position={[0.01, 0, 5.61]} rotation={[0, 0.06, 0]} scale={[0.18, 0.07, 1.22]}>
              <mesh geometry={nodes.Object_14.geometry} material={materials.material_2} />
            </group>
            <group position={[-0.06, 0, 4.47]} rotation={[0, 0.06, 0]} scale={[0.21, 0.08, 1.4]}>
              <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            </group>
            <group position={[0.08, 0, 6.69]} rotation={[0, 0.06, 0]} scale={[0.2, 0.07, 2.3]}>
              <mesh geometry={nodes.Object_20.geometry} material={materials['material_1.001']} />
            </group>
            <group position={[-0.07, 0, 4.22]} rotation={[-Math.PI, -0.06, -Math.PI]} scale={[0.21, 0.08, 1.4]}>
              <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
            </group>
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_28.geometry}
              material={materials.Material}
              skeleton={nodes.Object_28.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_29.geometry}
              material={materials.ACC_PC_ENE_CMA_B_B}
              skeleton={nodes.Object_29.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
