/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diox..Andrey (https://sketchfab.com/Diox..Andrey)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hero-warrior-downloadable-828017e697e64547b552aa868f045714
title: hero warrior (downloadable)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.default__0.geometry}
            material={materials['Scene_-_Root']}
            skeleton={nodes.default__0.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
