/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tnnv (https://sketchfab.com/tnnv)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/third-legion-legionnaire-16f711e693c1479ba61acfb8824b3885
title: Third Legion Legionnaire
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes.Body_Body_0.geometry}
              material={materials.Body}
              skeleton={nodes.Body_Body_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Vest001_M_Armor_0.geometry}
              material={nodes.Vest001_M_Armor_0.material}
              skeleton={nodes.Vest001_M_Armor_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Vest002_M_Armor_0.geometry}
              material={nodes.Vest002_M_Armor_0.material}
              skeleton={nodes.Vest002_M_Armor_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Vest004_M_Armor_0.geometry}
              material={nodes.Vest004_M_Armor_0.material}
              skeleton={nodes.Vest004_M_Armor_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Vest003_M_Armor_0.geometry}
              material={nodes.Vest003_M_Armor_0.material}
              skeleton={nodes.Vest003_M_Armor_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Vest008_M_Armor_0.geometry}
              material={nodes.Vest008_M_Armor_0.material}
              skeleton={nodes.Vest008_M_Armor_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Vest009_M_Armor_0.geometry}
              material={nodes.Vest009_M_Armor_0.material}
              skeleton={nodes.Vest009_M_Armor_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
