/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: antoinepavia (https://sketchfab.com/antoinepavia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/5b91e9ec25a14a6da18b4ca8e238e496
title: Heimjil
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="0"
            geometry={nodes['0'].geometry}
            material={materials.Body_MAT2}
            skeleton={nodes['0'].skeleton}
          />
          <skinnedMesh
            name="1"
            geometry={nodes['1'].geometry}
            material={materials.defaultMat}
            skeleton={nodes['1'].skeleton}
          />
          <skinnedMesh
            geometry={nodes['2'].geometry}
            material={materials.MaleBruteA_Bottom3}
            skeleton={nodes['2'].skeleton}
          />
          <skinnedMesh
            geometry={nodes['3'].geometry}
            material={materials.EyeSpec_MAT2}
            skeleton={nodes['3'].skeleton}
          />
          <skinnedMesh geometry={nodes['4'].geometry} material={materials.Material_27} skeleton={nodes['4'].skeleton} />
          <skinnedMesh
            geometry={nodes['5'].geometry}
            material={materials.MaleBruteA_Shoes4}
            skeleton={nodes['5'].skeleton}
          />
          <skinnedMesh geometry={nodes['6'].geometry} material={materials.warrok_MAT} skeleton={nodes['6'].skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
