/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Leonardo Carvalho (https://sketchfab.com/livrosparacriancas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fuse-warrior-6e8a032cedf9426fbc31ee3a49a4300d
title: .Fuse Warrior
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group name="Armature">
                  <group>
                    <primitive object={nodes._rootJoint} />
                    <group rotation={[Math.PI / 2, 0, 0]} />
                    <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Body} skeleton={nodes.Object_79.skeleton} morphTargetDictionary={nodes.Object_79.morphTargetDictionary} morphTargetInfluences={nodes.Object_79.morphTargetInfluences} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Bottom} skeleton={nodes.Object_80.skeleton} morphTargetDictionary={nodes.Object_80.morphTargetDictionary} morphTargetInfluences={nodes.Object_80.morphTargetInfluences} />
                    <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.material_5} skeleton={nodes.Object_81.skeleton} morphTargetDictionary={nodes.Object_81.morphTargetDictionary} morphTargetInfluences={nodes.Object_81.morphTargetInfluences} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.Shoes} skeleton={nodes.Object_82.skeleton} morphTargetDictionary={nodes.Object_82.morphTargetDictionary} morphTargetInfluences={nodes.Object_82.morphTargetInfluences} />
                  </group>
                </group>
                <group rotation={[Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
