/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SketchSupreme (https://sketchfab.com/sketchsupreme)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fortnite-black-knight-70-tier-battle-pass-skin-deacc97b8d264b45b4589a8fa5e09dc8
title: Fortnite Black Knight 70 Tier Battle Pass Skin
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group>
                    <primitive object={nodes._rootJoint} />
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh geometry={nodes.Object_176.geometry} material={materials.M_Med_Soldier_04} skeleton={nodes.Object_176.skeleton} />
                    <skinnedMesh geometry={nodes.Object_177.geometry} material={materials.M_Med_Soldier_Head} skeleton={nodes.Object_177.skeleton} />
                  </group>
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
