/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DRT.com (https://sketchfab.com/3DRT.com)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/3drt-fantasy-warrior-d39a0dee0f054c21b6751f7821aa7a8e
title: 3DRT - Fantasy Warrior
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.warrior_warrior_0.geometry}
            material={materials.warrior}
            skeleton={nodes.warrior_warrior_0.skeleton}
          />
          <skinnedMesh
            geometry={nodes.sword_warrior_0.geometry}
            material={materials.warrior_0}
            skeleton={nodes.sword_warrior_0.skeleton}
          />
          <skinnedMesh
            geometry={nodes.shield_warrior_0.geometry}
            material={materials.warrior_1}
            skeleton={nodes.shield_warrior_0.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
